api-version: '1.13'
description: 'Allows plugins to create configurations and languages, report errors, handle commands and send messages more easily.'
name: EpicPluginAPI
author: Epicnicity322
main: com.epicnicity322.epicpluginapi.EpicPluginAPI
version: '1.3-SNAPSHOT'
website: https://github.com/Epicnicity322/EpicPluginAPI